name: Java CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      # From https://stackoverflow.com/a/65740844
      - name: Extract Maven project version
        run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        id: project
      - name: Show extracted Maven project version
        run: echo ${{ steps.project.outputs.version }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64,arm
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and test Docker image
        uses: docker/build-push-action@v3
        with:
          platforms: linux/arm64,linux/amd64 #,linux/arm/v8
          target: build
          # relative path to the place where source code with Dockerfile is located
          context: .
      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          platforms: linux/arm64,linux/amd64 #,linux/arm/v8
          # relative path to the place where source code with Dockerfile is located
          context: .
          tags: |
            stevenmassaro/email:latest
            stevenmassaro/email:${{ steps.project.outputs.version }}
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/master' }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
